server:
  port: ${SERVER_PORT:8888}
  
spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: API-GATEWAY
  zipkin:
    base-url: ${ZIPKIN_URL:http://zipkin:9411/}
  cloud:
    gateway:
      enabled: true
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates: 
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: default
                timeLimiter: 
                  timeoutDuration: 50ms
                  cancelRunningFuture: true
        - id: DEPARTAMENT-SERVICE
          uri: lb://DEPARTAMENT-SERVICE
          predicates:
            - Path=/departaments/**
          filters:
            - name: CircuitBreaker
              args:
                name: default
                timeLimiter: 
                  timeoutDuration: 50ms
                  cancelRunningFuture: true

resilience4j:
  circuitbreaker:
    instances:
      default:
        slidingWindowSize: 10                     #unit request
        permittedNumberOfCallsInHalfOpenState: 5  #unit request
        failureRateThreshold: 50                  #percent
        waitDurationInOpenState: 10000            #10 seconds
        registerHealthIndicator: true

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_HOSTNAME:eureka-0}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka
    
management:
  endpoints:
    web: 
      exposure:
        include:
        - "*"
  tracing:
    propagation:
      type: w3c
    enabled: true
    sampling.probability: 1.0

  zipkin.tracing.endpoint: ${ZIPKIN_URL:http://localhost:9411}/api/v2/spans
  
logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
