server:
  port: 8021
  
spring:
  application:
    name: DEPARTMENT-SERVICE
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: 6379
      
management:
  tracing:
    enabled: true
    sampling.probability: 1.0

  zipkin.tracing.endpoint: ${ZIPKIN_HOST:http://localhost:9411}/api/v2/spans
  
logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_HOSTNAME:eureka-0}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka